Import numpy as np and see the version

In [2]:
import numpy as np

In [4]:
print(np.version.version)

1.15.1


In [5]:
print(np.__version__)

1.15.1


Create a 1D array of numbers from 0 to 9

In [6]:
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create 1D array every two numbers from 3 to 100

In [9]:
np.arange(3,100,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69,
       71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

Create a 3×3 numpy array of all True’s

In [12]:
np.array([[1,1,1],[1,1,1],[1,1,1]],dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

https://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html

In [14]:
np.full((3, 3), True, dtype=bool)


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [15]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Extract all odd numbers from arr

In [20]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for x in np.nditer(arr):
    if(x%2!=0):
        print(x)

1
3
5
7
9


In [21]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

Replace all odd numbers in arr with -1

In [23]:
with np.nditer(arr, op_flags=['readwrite']) as it:
    for x in it:
        if(x%2!=0):
            x[...]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [24]:
arr[arr % 2 == 1] = -1

Replace all odd numbers in arr with -1 without changing arr


In [30]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])